### ISSUE TITLE
How to Start Gatsby Project with Gravity UI?

### ISSUE THREAD

**Issue by Saifrao1** [gravity-ui/uikit#1300] opened 2024-02-01 17:22 UTC
Hi everyone! 👋 I'm new to Gatsby and I'm trying to use the Gravity UI in my project. I'm having trouble getting started, and I could use some guidance on how to set up a Gatsby project with Gravity UI.

Here are the steps I've tried so far:
Installed Gatsby using gatsby new my-app --example "https://github.com/gravity-ui/gravity-ui-nextjs-example"
Added the Gravity UI package using npm install gravity-ui
However, I'm unsure about how to integrate Gravity UI components into my Gatsby project. Are there specific steps or configurations I should be aware of?

Questions:

How do I import and use Gravity UI components in my Gatsby project?
Are there any specific configurations or dependencies I need to be aware of?
How i sue Container as they say "Container
Center you content. Almost always it should be one per page. Manage max width corresponding to current screen size"
soo if i have use layout component and i wrap my nav-bar in Container Component nd apply mx-width = 'xxl' and i want to apply background color to nav soo its not cover the whole width insted its only cover the Container width

**Comment by amje** [comment] 2024-03-05 16:54
Duplicate of #1313

**Closed by amje** 2024-03-05 16:54 UTC
Labels: question
